services:
    poznet.array.paginator:
        class: Poznet\ArrayPaginatorBundle\Services\ArrayPaginator

    poznet.paginator.twig_extension:
            class: Poznet\ArrayPaginatorBundle\Twig\Extension\ArrayPaginationExtension
            arguments: [ @service_container ]
            tags:
                - { name: twig.extension }