services:
    poznet.array.paginator:
        class: Poznet\ArrayPaginatorBundle\Services\ArrayPaginator
        arguments: ['%poznet_array_paginator_perpage%']

    poznet.paginator.twig_extension:
            class: Poznet\ArrayPaginatorBundle\Twig\Extension\ArrayPaginationExtension
            arguments: [ @poznet.array.paginator ]
            tags:
                - { name: twig.extension }

